--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: elasticsearch-snapshot
  namespace: elasticsnapshot
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 200Mi
  storageClassName: standard
