---
imageTag: "7.12.0"
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"
nodeGroup: "master"
replicas: 2

# Shrink default JVM heap.
esJavaOpts: "-Xmx256m -Xms256m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1G"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 200M

# This is just a dummy file to make sure that
# the keystore can be mounted at the same time
# as a custom elasticsearch.yml
esConfig:
  elasticsearch.yml: |
      path.repo: /usr/share/elasticsearch/snapshot

#Add Volument
extraVolumes:
  - name: elastic-backup
    persistentVolumeClaim:
      claimName: elasticsearch-snapshot
extraVolumeMounts:
  - name: elastic-backup
    mountPath: /usr/share/elasticsearch/snapshot

